_wandb:
    value:
        cli_version: 0.28.2
        e:
            8za6pdk3ytwgmwz9h3nkz5lm6g4qvwjn:
                cpu_count: 14
                cpu_count_logical: 18
                disk:
                    /:
                        total: "473391165440"
                        used: "323464929280"
                email: amdggourav@gmail.com
                executable: C:\Users\Gourav\AppData\Local\Python\pythoncore-3.14-64\python.exe
                git:
                    commit: bd8fa83fe46adbf10a0b3042e4667b000e53dc30
                    remote: https://github.com/Kavana-Padmakumar/physioshift.git
                host: LAPTOP-VPK5UVPK
                memory:
                    total: "16569610240"
                os: Windows-11-10.0.26100-SP0
                program: -m src.train.train_baseline
                python: CPython 3.14.3
                root: C:\Users\Gourav\Downloads\physioshift
                startedAt: "2026-08-22T12:14:53.536377Z"
                writerId: 8za6pdk3ytwgmwz9h3nkz5lm6g4qvwjn
        m: []
        python_version: 3.14.3
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 16
            "4": 3.14.3
            "5": 0.28.2
            "8":
                - 3
            "12": 0.28.2
            "13": windows-amd64
batch_size:
    value: 16
epochs:
    value: 3
lr:
    value: 0.001
num_classes:
    value: 5
patience:
    value: 3
smoke_test_size:
    value: 50
